version: "3.8"
services:
  server:
    build:
      context: server/.
    ports:
      - 3001:3001
    volumes:
      - ./server:/usr/app
      - ./usr/app/node_modules
  client:
    build:
      context: ./client/.
    ports:
      - 3000:3000
    depends_on:
      - server
    volumes:
      - ./client:/usr/app
      - ./usr/app/node_modules
